drop table `sp-ed-opssupplyanalytics-dev.supply_sap.po_line_helper`;
create table `sp-ed-opssupplyanalytics-dev.supply_sap.po_line_helper` (
  po_number string not null,
  po_created_by string not null,
  po_created_dt string not null,
  po_doc_type string not null,
  po_vendor_code string not null,
  po_vendor_name string,
  po_term_of_payments string not null,
  po_purchase_org string not null,
  po_purchase_group string not null,
  po_currency string not null,
  po_ack string,
  po_ln_number string,
  po_ln_deletion_indicator string,
  po_ln_material string,
  po_ln_shor_text string,
  po_ln_material_group string,
  po_ln_location string,
  po_ln_qty numeric(15,3),
  po_ln_unit string,
  po_ln_net_price numeric(15,3),
  po_ln_net_worth numeric(15,3),
  po_ln_delivery_dt string,
  po_ln_delivered_qty numeric(15,3),
  req_number string,
  req_ln string,
  req_material string,
  req_manufacturer string,
  req_manufacturer_part_profile string,
  req_qty numeric(15,3),
  req_created_by string,
  req_created_dt string,
  req_released_dt string,
  req_delivery_dt string,
  req_location string,
  req_doc_type string,
  mt_valuation_class string,
  created_at datetime,
  updated_at datetime,
)
cluster by po_created_dt, po_number, po_ln_number, po_ln_material

